#!/usr/bin/env ruby

require 'rubygems'

# Load hbase client libs generated by thrift
$LOAD_PATH << File.join(File.dirname(__FILE__), 'hbase')
require 'hbase'

#--------------------------------------------------------------------------------
# Connect to hbase
socket = ::Thrift::Socket.new('localhost', 9090, 5) # server, port, timeout
transport = ::Thrift::BufferedTransport.new(socket)
transport.open

protocol = ::Thrift::BinaryProtocol.new(transport)
client = Apache::Hadoop::Hbase::Thrift::Hbase::Client.new(protocol)

#--------------------------------------------------------------------------------
# Get a row from hbase

def get(client, start_key, end_key)
  scanner = client.scannerOpenWithStop('table', start_key, end_key, []) # Get all columns for row_id='123'
  results = client.scannerGetList(scanner, 100)
  results.each {|r| puts r.row}
  client.scannerClose(scanner)
end

get(client, '13147', '13149')
